name: "coverage"
on:
  pull_request:
    branches:
      - main
jobs:
  coverage:
    permissions:
      contents: write
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yarn-install
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: yarn jest
          package-manager: yarn
          annotations: coverage
          working-directory: packages/frontend
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: yarn jest
          package-manager: yarn
          annotations: coverage
          working-directory: packages/api-client
