name: "Test Build"
on: ["push"]
jobs:
  Compile-Test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      # Equivalent of README.md Starting steps.
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - run: yarn install --immutable

      # Attempt to build this branch.
      - run: yarn build
