name: "Test Build"
on: ["push"]
jobs:
  Compile-Test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      # Equivalent of README.md Starting steps.
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          # cache: "yarn"

      - run: corepack enable
      - run: corepack prepare yarn@4.0.2 --activate
      - run: yarn install --immutable
      - run: yarn install --immutable # Install twice because reasons...

      # Here for only debug purposes...
      - run: node --version
      - run: yarn --version
      - run: yarn exec tsc --version
      - run: cat packages/backend/tsoa.json

      # Attempt to build this branch.
      - run: yarn workspace @esp-group-one/types build
      - run: yarn workspace @esp-group-one/api-client build
      - run: yarn workspace @esp-group-one/db-client build
      - run: yarn workspace @esp-group-one/config build
      - run: yarn build -v
