name: "Test Build"
on: ["push"]
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/yarn-install
      - name: Lint packages
        run: yarn test
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/yarn-install
      - name: Lint packages
        run: yarn lint-ci
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/yarn-install
      - name: Run tests
        run: yarn test
